name: LifeMod
authors: [Lampalon]
version: '1.7.0-RELEASE'
main: fr.lampalon.lifemod.bukkit.LifeMod
api-version: '1.13'
softdepend:
  - LuckPerms
commands:
  mod:
    description: Moderate your server
    aliases: ["staff"]
  broadcast:
    aliases: ["bc"]
    description: Produces a message for the entire server.
  gm:
    aliases: ["gamemode"]
    description: Changes the game mode.
  fly:
    description: Allows you to fly.
  ecopen:
    description: Open a person's ec
  vanish:
    aliases: ["v"]
    description: Vanish you or other player.
  clearinv:
    description: Clear inventory for a player or yourself.
  stafflist:
    description: View moderators online.
  staffchat:
    description: chatting with other staffs.
  chatclear:
    description: To clear the chat.
  togglechat:
    description: To activate or not the chat.
  heal:
    description: To heal a player or yourself.
  tp:
    description: To tp to a person.
  tphere:
    description: Tp person to you.
  weather:
    description: To change the time.
  god:
    description: To activate or deactivate god for invincibility.
  freeze:
    description: To freeze and unfreeze player.
  invsee:
    description: To see inventory of a player.
  feed:
    description: To feed you or other player.
  lifemod:
    description: use Lifemod for help or reload.
  speed:
    description: permit you to update your speed.
  spectate:
    description: See player from a command.
  otp:
    description: teleport to an offline player.
  oinvsee:
    description: See the inventory of a offline player.
  hearts:
    description: "Manage player hearts: set or add a specific amount of hearts to any player."
  settime:
    description: Quickly set the world time to day, night, noon, or midnight.
  difficulty:
    description: Change the server difficulty to peaceful, easy, normal, or hard.
  report:
    description: Report a player
  reports:
    description: see all reports
  modlogin:
    description: Authenticate as a moderator.
    usage: /modlogin <password>
    permission: lifemod.moderator
  modregister:
    description: Register your moderator password.
    usage: /modregister <password>
    permission: lifemod.moderator
  modchangepass:
    description: Change your moderator password.
    usage: /modchangepass <old> <new>
    permission: lifemod.moderator
  modreset:
    description: Reset a moderator's password (admin only).
    usage: /modreset <player>
    permission: lifemod.admin
  follow:
    description: follow a player with somes informations.
    usage: /<command>
permissions:
  lifemod.*:
    default: op
    children:
      - lifemod.fly
      - lifemod.fly.others
      - lifemod.gm
      - lifemod.mod
      - lifemod.bc
      - lifemod.ecopen
      - lifemod.vanish
      - lifemod.clearinv
      - lifemod.staffchat
      - lifemod.heal
      - lifemod.tp
      - lifemod.tphere
      - lifemod.weather
      - lifemod.god
      - lifemod.freeze
      - lifemod.invsee
      - lifemod.feed
      - lifemod.chat.views
      - lifemod.chat.bypass
      - lifemod.invsee.interact
      - lifemod.notify
      - lifemod.spectate
      - lifemod.otp
      - lifemod.oinvsee
      - lifemod.time
      - lifemod.difficulty
      - lifemod.hearts
      - lifemod.togglechat.bypass
      - lifemod.togglechat
      - lifemod.staff
      - lifemod.reports
      - lifemod.stafflist
      - lifemod.report.join
      - lifemod.moderator
      - lifemod.admin