name: LifeMod
author: Lampalon
version: '1.3.2-RELEASE'
main: fr.lampalon.lifemod.LifeMod
commands:
  mod:
    description: Moderate your server
  broadcast:
    aliases: ["bc"]
    description: Produces a message for the entire server.
  gm:
    aliases: ["gamemode"]
    description: Changes the game mode.
  fly:
    description: Allows you to fly.
  ecopen:
    description: Open a person's ec
  vanish:
    aliases: ["v"]
    description: Vanish you or other player.
  clearinv:
    description: Clear inventory for a player or yourself.
  stafflist:
    description: View moderators online.
  staffchat:
    description: chatting with other staffs.
  chatclear:
    description: To clear the chat.
  togglechat:
    description: To activate or not the chat.
  heal:
    description: To heal a player or yourself.
  tp:
    description: To tp to a person.
  tphere:
    description: Tp person to you.
  weather:
    description: To change the time.
  god:
    description: To activate or deactivate god for invincibility.
  freeze:
    description: To freeze and unfreeze player.
  invsee:
    description: To see inventory of a player.
  feed:
    description: To feed you or other player.
permissions:
  lifemod.*:
    default: op
    children:
      - lifemod.fly
      - lifemod.gm
      - lifemod.mod
      - lifemod.bc
      - lifemod.ecopen
      - lifemod.vanish
      - lifemod.clearinv
      - lifemod.staffchat
      - lifemod.heal
      - lifemod.tp
      - lifemod.tphere
      - lifemod.weather
      - lifemod.god
      - lifemod.freeze
      - lifemod.invsee
      - lifemod.feed